version: "3.9"

services:
  mysql:
    image: "mysql:8.2.0"
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
  
  mysql-proxy:
    image: "database/mysql-proxy"
    environment:
      - "PORT=${PORT}"
      - "MYSQL_ROOT_URI=${MYSQL_ROOT_URI}"
    ports:
      - "${PORT}:${PORT}"

volumes:
  mysql-data: